BotaniFinder/Controllers/PlantIdentificationController.cs
using BotaniFinder.Context;
using BotaniFinder.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace BotaniFinder.Controllers
{
    public class PlantIdentificationController : Controller
    {
        //The BotaniFinderDbContext is injected into the controller using dependency injection, with the constructor.
        //This follows the Dependency Inversion Principle in the SOLID principles.
        private readonly BotaniFinderDbContext _dbContext;
        private readonly string _plantNetApiUrl = "";

        public PlantIdentificationController(BotaniFinderDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        //IActionResult is a return type that can return a JSON object or View
        public IActionResult Index()
        {
            return View();
        }
        //HttpPost specifies that the method is only called when the HTTP request is a POST.
        [HttpPost]
        public async Task<IActionResult> Index(IFormFile image)
        {
            // if the image is null or the length is 0, an error message is added to the ModelState.
            if (image == null || image.Length == 0)
            {
                ModelState.AddModelError("image", "Please select a file to upload.");
                return View();
            }



            // OpenReadStream is used to open the file as a stream.
            using var stream = image.OpenReadStream();
            // httpClient sends and receives HTTP requests and responses.
            using var httpClient = new HttpClient();
            //The MultipartFormDataContent class is used to send data requests.
            using var content = new MultipartFormDataContent();
            //The StreamContent class is used to send the image as a stream.
            content.Add(new StreamContent(stream), "images", image.FileName);

            //MediaTypeWithQualityHeaderValues are used to specify the type of the response in this case it's application/json.
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            // response is the result of the POST request. It's Async because it's a task.
            var response = await httpClient.PostAsync(_plantNetApiUrl, content);


            //If the response is not successful, an error message is added.
            if (!response.IsSuccessStatusCode)
            {
                ModelState.AddModelError("image", "Error occurred while calling the PlantNet API.");
                return View();
            }


            //The response is read as a string and then deserialized into a Root object. 
            //The Root object is then used to create a new PlantIdentificationResult object.
            //This is the await from the Async task.
            var responseContent = await response.Content.ReadAsStringAsync();
            var plantIdentificationResult = JsonConvert.DeserializeObject<Root>(responseContent);
            var newPlantIdentificationResult = new PlantIdentificationResult
            {
                //These are the properties of the PlantIdentificationResult object.
                // The plantIdentificationResult.Results is a list of Result objects.
                Score = plantIdentificationResult.Results[0].Score,
                Species = plantIdentificationResult.Results[0].Species,
                Image = plantIdentificationResult.Results[0].Image,
            };
            //save changes to database and return the view.
            var newUrl = new Url
            {
                O = plantIdentificationResult.Results[0].Image[0].Url.O,
                M = plantIdentificationResult.Results[0].Image[0].Url.M,
                S = plantIdentificationResult.Results[0].Image[0].Url.O,
            };
            _dbContext.Urls.Add(newUrl);
            await _dbContext.SaveChangesAsync();
            // This is the await from the Async task in the Index method.
            return View(plantIdentificationResult);
        }
    }
}

BotaniFinder/Controllers/PreviousIdentificationsFromDatabaseController.cs
using BotaniFinder.Context;
using BotaniFinder.Models;
using Microsoft.AspNetCore.Mvc;

namespace BotaniFinder.Controllers
{
    //This controller only has one purpose, which is to return the previous identifications from the database.
    //This uses the Single Responsibility Principle in the SOLID principles.
    public class PreviousIdentificationsFromDatabaseController : Controller
    {
        //The BotaniFinderDbContext is injected into the controller using dependency injection, with the constructor.
        //This follows the Dependency Inversion Principle in the SOLID principles.
        private readonly BotaniFinderDbContext _context;

        public PreviousIdentificationsFromDatabaseController(BotaniFinderDbContext context)
        {
           
            _context = context;
        }
        public IActionResult Index()
        {
            //images takes the Urls table from the database and creates a new Url object with the UrlId and O properties.
            var images = _context.Urls.Select(u => new Url
            {
                UrlId = u.UrlId,
                O = u.O ?? ""
                //The new object is then added to a list.
            }).ToList();
            //The list is then returned to the view.
            return View(images);
        }
    }
}

BotaniFinder/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using System.Web.Mvc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BotaniFinder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BotaniFinder.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-mediumpurple border-bottom box-shadow mb-1 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BotaniFinder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlantIdentification" asp-action="Index">ID Your Plant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PreviousIdentificationsFromDatabase" asp-action="Index"> Previously Identified Plants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"> Helpful Links</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BotaniFinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">More Info</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>